[package]
name = "trading_grpc_server"
version = "0.1.23"
edition = "2024"
build = "build.rs"

[dependencies]
dotenv.workspace = true
prost.workspace = true
tonic.workspace = true
tokio = { workspace = true }
tokio-stream.workspace = true


[build-dependencies]
tonic-build = "0.13.1"